[package]
name = "binaries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[build]
target = "wasm32-wasi"

[dependencies]
wee_alloc = "0.4"

[profile.release]
lto = true
opt-level = 's'
